#!/usr/bin/env node
// gs-init: generated file (MIT). Regenerated by `node tools/gs-init/gs-init.mjs`; your edits are backed up before it is replaced.
// The project gates: spec shape, open questions, ratchet floor, typed commit messages, your test command. No dependencies, no model.
import fs from 'node:fs';
import path from 'node:path';
import cp from 'node:child_process';
(function () {
  const root = process.env.GS_ROOT || process.cwd();
  const cmd = process.argv[2] || 'all', arg = process.argv[3];
  const fail = m => { console.error('gs-gate: ' + m); process.exit(1); };
  const rd = rel => fs.readFileSync(path.join(root, rel), 'utf8').replace(/^﻿/, '').replace(/\r/g, '');
  const ex = rel => fs.existsSync(path.join(root, rel));
  const jr = rel => { try { return JSON.parse(rd(rel)); } catch { return null; } };
  const cfg = jr('.gs.json') || {};
  const SKIP = /^(node_modules|\.git|\.gs-init-backup|vendor|dist|build|bin|obj|target|\.venv|venv|__pycache__|coverage|tools)$/;
  const walk = (rel, filter, acc = []) => {
    let es = []; try { es = fs.readdirSync(path.join(root, rel), { withFileTypes: true }); } catch { return acc; }
    for (const e of es) { const p = rel ? rel + '/' + e.name : e.name; if (e.isDirectory()) { if (!SKIP.test(e.name)) walk(p, filter, acc); } else if (filter(p)) acc.push(p); }
    return acc;
  };
  const REQ = /^#{1,6} +\**([FN]-\d{3})(?!\.\d)/, CRIT = /^[ >|*_[xX-]*\**([FN]-\d{3}\.\d+)/;
  const specFiles = () => walk('docs/spec', p => p.endsWith('.md'));
  const criteria = () => { const ids = []; for (const f of specFiles()) for (const l of rd(f).split('\n')) { const m = l.match(CRIT); if (m && /verified by:/i.test(l)) ids.push(m[1]); } return ids; };

  const spec = () => {
    if (!ex('docs/spec/SPEC.md')) fail('docs/spec/SPEC.md is missing');
    const reqs = new Set(), crits = new Set(), seen = new Set();
    for (const f of specFiles()) for (const [i, l] of rd(f).split('\n').entries()) {
      const r = l.match(REQ); if (r) reqs.add(r[1]);
      const c = l.match(CRIT); if (!c) continue;
      if (!/\b(MUST|SHOULD|MAY|DEBE|DEBERÍA|PUEDE)\b/.test(l)) fail(f + ':' + (i + 1) + ': criterion ' + c[1] + ' has no MUST, SHOULD or MAY');
      if (!/verified by:/i.test(l)) fail(f + ':' + (i + 1) + ': criterion ' + c[1] + ' has no "verified by:"');
      if (seen.has(c[1])) fail(f + ':' + (i + 1) + ': criterion id ' + c[1] + ' is defined twice (ids are never reused)');
      seen.add(c[1]); crits.add(c[1].split('.')[0]);
    }
    if (!reqs.size) fail('no requirement heading with an id (## F-001 ...) in docs/spec');
    for (const r of reqs) if (!crits.has(r)) fail('requirement ' + r + ' has no criterion (a list line starting F-nnn.n)');
  };
  const open = () => {
    const files = [...specFiles(), ...(ex('docs/open-questions.md') ? ['docs/open-questions.md'] : [])];
    for (const f of files) for (const [i, l] of rd(f).split('\n').entries()) if (/^\s*(?:[-*]\s*)?OPEN:/.test(l)) fail(f + ':' + (i + 1) + ': an open question blocks the work: ' + l.trim());
  };
  const TESTRE = {
    node: /^\s*(?:test|it)(?:\.\w+)*\s*\(/gm, python: /^\s*(?:async\s+)?def\s+test_/gm, go: /^func\s+Test\w+/gm,
    dotnet: /\[\s*(?:Fact|Theory|Test|TestCase|TestMethod)\b/g,
  };
  const isTestFile = p => /(^|\/)(tests?|__tests__|spec)\//i.test(p) || /(\.|_)(test|spec)\.[a-z]+$/i.test(p) || /(^|\/)test_[^/]*\.py$/.test(p) || /Tests?\.cs$/.test(p);
  const measure = () => {
    const re = TESTRE[cfg.stack] ? [TESTRE[cfg.stack]] : Object.values(TESTRE);
    let n = 0;
    for (const f of walk('', p => isTestFile(p) && /\.(m?[jt]sx?|cjs|py|go|cs)$/.test(p))) { const t = rd(f); for (const r of re) n += (t.match(r) || []).length; }
    return { tests: n, criteria: criteria().length };
  };
  const ratchet = () => {
    const cur = measure();
    if (arg === '--init') {
      if (ex('docs/baseline.json')) return console.log('gs-gate: docs/baseline.json already exists; floors unchanged');
      fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
      fs.writeFileSync(path.join(root, 'docs/baseline.json'), JSON.stringify({ floors: cur, ceilings: {} }, null, 2) + '\n');
      return console.log('gs-gate: docs/baseline.json created with floors ' + JSON.stringify(cur));
    }
    const b = jr('docs/baseline.json'); if (!b || typeof b.floors !== 'object') fail('docs/baseline.json is missing or not {"floors": {...}, "ceilings": {...}}');
    if (arg === '--raise') {
      for (const k of Object.keys(cur)) b.floors[k] = Math.max(b.floors[k] || 0, cur[k]);
      fs.writeFileSync(path.join(root, 'docs/baseline.json'), JSON.stringify(b, null, 2) + '\n');
      return console.log('gs-gate: floors raised to ' + JSON.stringify(b.floors));
    }
    for (const k of Object.keys(b.floors)) if ((cur[k] ?? 0) < b.floors[k]) fail('ratchet: ' + k + ' is ' + (cur[k] ?? 0) + ', below the floor ' + b.floors[k] + ' (raise the number with real tests or specs; never lower the floor)');
    for (const k of Object.keys(b.ceilings || {})) if ((cur[k] ?? 0) > b.ceilings[k]) fail('ratchet: ' + k + ' is ' + cur[k] + ', above the ceiling ' + b.ceilings[k]);
    const head = cp.spawnSync('git', ['show', 'HEAD:docs/baseline.json'], { cwd: root, encoding: 'utf8' });
    if (head.status === 0) {
      let old = null; try { old = JSON.parse(head.stdout.replace(/^﻿/, '')); } catch { /* old file unreadable */ }
      for (const k of Object.keys((old && old.floors) || {})) if ((b.floors[k] ?? 0) < old.floors[k]) fail('ratchet: floor ' + k + ' was lowered from ' + old.floors[k] + ' to ' + (b.floors[k] ?? 0) + '; the floor only goes up');
      for (const k of Object.keys((old && old.ceilings) || {})) if (!(k in (b.ceilings || {})) || b.ceilings[k] > old.ceilings[k]) fail('ratchet: ceiling ' + k + ' was raised or removed; the ceiling only goes down');
    }
  };
  const test = () => {
    const c = cfg.gate && cfg.gate.test; if (!c) return console.log('gs-gate: no test command set (gate.test in .gs.json); tests not run');
    const env = Object.assign({}, process.env); delete env.NODE_TEST_CONTEXT;
    const r = cp.spawnSync(c, { cwd: root, shell: true, stdio: 'inherit', env });
    if (r.status !== 0) fail('tests failed: ' + c);
  };
  const commitMsg = () => {
    if (!arg) fail('commit-msg needs the message file');
    const subject = rd(arg).split('\n').find(l => l.trim() && !l.startsWith('#')) || '';
    if (/^(Merge|Revert|fixup!|squash!)\b/.test(subject)) return;
    if (!/^(feat|fix|docs|refactor|test|chore|build|ci|perf|style|revert)(\([^)]+\))?!?: \S.{2,}/.test(subject)) fail('the commit subject must read "type: what changed" (feat fix docs refactor test chore build ci perf style revert). Got: ' + subject);
  };
  const cheap = () => { spec(); open(); ratchet(); };
  const table = { spec, open, ratchet, test, 'commit-msg': commitMsg, 'pre-commit': () => { cheap(); test(); }, 'pre-push': () => { cheap(); test(); }, all: () => { cheap(); test(); } };
  if (!table[cmd]) fail('unknown command ' + cmd + ' (spec open ratchet test commit-msg pre-commit pre-push all)');
  table[cmd]();
  if (cmd !== 'commit-msg' && !['--init', '--raise'].includes(arg)) console.log('gs-gate: ' + cmd + ' ok');
})();
